### ISSUE TITLE
H812 Nougat - Video Recording fails in Google Camera

### ISSUE THREAD

**Issue by vsTerminus** [Suicide-Squirrel/issues_oreo#10]
This is an issue that seems to be fairly specific to the H812, unlocked by UsU method. It affects other ROMs as well since you guys use the same sources for all of the custom G4 ROMs. (I have personally tested it on LOS and AOSCP)

Basically:

Trying to record video with any Google Camera based app, or any other camera app which uses the Camera2 API, will fail.

You'll either get 
- a message immediately when you try to start recording that the app cannot record video
- it will seem to start recording just fine, but when you stop the recording you get an unplayable file

Switching to "legacy mode" or disabling Camera2 API seems to be a functional workaround, but even then there seems to be issues with low framerate and stuttering in some apps. 

Yes, Cinema FV5 works "well enough" to be an ok workaround for most people, but it is inferior to GCam and isn't that stable for me. I'm hoping that we can find a solution, not another workaround.

Attached you will find a logcat from a fresh install of AOSCP Nougat on the H812. I did a full wipe and format, and flashed only the ROM. The logcat captures booting up, attempting to record video in GCam, and then shutting down. I performed this before and after installing GApps to ensure that wasn't part of the problem. Both logs are attached. You can also find more info on *exactly* what I did [in this XDA post](https://forum.xda-developers.com/g4/general/unlock-unlock-lg-g4-device-usu-t3760451/post76225151#post76225151).

H812 AOSCP Logcats:
[h812-aoscp-nougat-camera-adb-logs.zip](https://github.com/Suicide-Squirrel/issues_oreo/files/2065402/h812-aoscp-nougat-camera-adb-logs.zip)

If there is anything else I can provide, please let me know.

**Comment by steadfasterX** [comment]
Sorry didn't realized that you spoke about N. Do you have you the same issues on O?

**Comment by sreehax** [comment]
try to disable `camcorder.h265` and `camcorder.fastswitch` in the google camera "developer config". The "developer config" could be named different depending on which google camera build you use. The google camera that ships with opengapps doesn't seem to have developer config, try a different build

**Comment by steadfasterX** [comment]
closed due to inactivity
