### ISSUE TITLE
Video Recording doesn't work (VS986)

### ISSUE THREAD

**Issue by monsteroko** [Suicide-Squirrel/issues_oreo#17]
On VS986 video recording doesn't work on lineage or any other rom, on stock and on goggle camera apps. 
On Stock rom (v29a) I have a mobile data, but can't call anyone.

**Comment by steadfasterX** [comment]
still an issue? if so try that on LOS:

https://github.com/Suicide-Squirrel/issues_oreo/issues/11#issuecomment-482486471

**Comment by steadfasterX** [comment]
closed as no response. feel free to re-open
