### ISSUE TITLE
Encryption may soft brick the phone.

### ISSUE THREAD

**Issue by fatihbalsoy** [Suicide-Squirrel/issues_oreo#18]
I decided to encrypt my H811 right after I installed LineageOS 15.1 with Stock OpenGapps and Magisk, which worked fine. However, after the green Android appears I would always see a kernel crash, proceed to the LineageOS boot animation and it freezes. The only way I was able to get back to the OS was to go into recovery mode, format partitions, reinstall packages, and restore from the backup I did before the encryption. Unfortunately, I wasn't able to capture any logs during the process of booting from the kernel crash.

**Comment by sreehax** [comment]
I have this exact same issue.

**Comment by steadfasterX** [comment]
dup of #13
