### ISSUE TITLE
MAC address auto change after encrypting/formatting data

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_oreo#2]
https://forum.xda-developers.com/g4/development/lineageos-15-1-lg-g4-t3782722/post76637578

**Comment by ThePiGuy0** [comment]
After multiple reboots, my mac addresses have not changed

**Comment by steadfasterX** [comment]
damn for me it changes!

**Comment by steadfasterX** [comment]
## Reason

This can happen when manually formatting /data (i.e. in TWRP "Format data" button) or (depending on the ROM and/or TWRP version) when enabling encryption.

## Solution (recommended)

Boot to TWRP and mount: Data

```
adb shell
hexdump -s 0x3000 -n 6 -e '"cur_etheraddr=" 5/1 "%02x:" 1/1 "%02x\n"' /dev/block/bootdevice/by-name/misc > /data/misc/wifi/config
```

Verify (while still in that adb shell):

```
cat /data/misc/wifi/config

result:
cur_etheraddr=00:90:4c:cc:bb:aa
(yours will look different)
```

## Solution (alternative)

If the above does not work for you try this instead:

Boot to TWRP and mount: System + Data

```
adb shell
grep macaddr= /system/etc/wifi/bcmdhd.cal | sed 's/macaddr=/cur_etheraddr=/g' > /data/misc/wifi/config
```
Verify (while still in that adb shell):

```
cat /data/misc/wifi/config

result:
cur_etheraddr=00:90:4c:cc:bb:aa
(yours will look different)
```
