### ISSUE TITLE
Lock Screen (pin) stops working after a number of system bootups ...

### ISSUE THREAD

**Issue by sdembis** [Suicide-Squirrel/issues_oreo#23]
Seems to have started happening again with no way to ascertain when & why exactly it happens.  Normally appears after a variable period of time (can be a day to a week +) and requires manual reboot into TWRP and removing the locksettings.db files in data/system.  
It appears after both dirty flash and clean flash (including format Data >Yes). 
One thing I have noticed is the gatekeeper lock screen files that used to be in data/system are no longer present but not sure if their removal is related to this recurring issue.
You are able to open the lockscreen and enter the pin but on entering it the screen just refreshes and does the same thing again until the locksetting files are removed in TWRP
If I can provide any useful logs given the inability to know when it will happen when nothing seems to be responsible for triggering it, PM me on XDA, @sdembiske

**Comment by rundumdieuhr** [comment]
> One thing I have noticed is the gatekeeper lock screen files that used to be in data/system are no longer present but not sure if their removal is related to this recurring issue.

I wanna confirm that, on my G4, lock screen configuration *with* lockscreen.db only and *without* any other (former) pattern/gatekeeper files present works fine! So I'd guess no, unrelated. :)
@sdembis So, luckily, I haven't come across that issue you are experiencing, seems to be an odd one. Might you have been switching around backups or flashing some uncommon add-on / mod?

> You are able to open the lockscreen and enter the pin but on entering it the screen just refreshes and does the same thing again until the locksetting files are removed in TWRP

Cause I know what you mean here. I only experienced that behaviour once, when steadfasterX was debugging the issue with the initial video lag fix and had me try some patches that flashed files into /data or some other root subdirectory. After resetting the lockscreen.db back then, I haven't seen it ever again, despite all backup and ROM flashing. I'll keep my fingers crossed for your setup, but to me it doesn't seem to be a common issue.

**Comment by sdembis** [comment]
I have been not been switching around backups or flashing some uncommon add-on / mods.
I always make sure I do a regular or full clean wipe and and flash the video-lag fix after installing the rom and Open Gapps.
Now I'm also getting in addition to the lock screen issue from time to time a blue screen with excessive battery drain at that instance. 
Note:  I was not having these issues before the video-lag fix so and have done nothing different or added any new apps etc rather than the normal course Google Play Store app updates.
At a loss as to why it's occurring now.

**Comment by rundumdieuhr** [comment]
> Note: I was not having these issues before the video-lag fix

So possibly the issue is really related to the video-lag fix (rather than the ROM itself). I apply it without issues on the H815 (btw, I flash the video-lag fix before gapps). I think you got the North American variant. So should we maybe compare files in Internal Storage/Download/LG-G4_VideoLag-Fix_backup_... or some kind of log? @steadfasterX what do you think?

**Comment by steadfasterX** [comment]
@sdembis 

using the issue here is a much easier (for me) way to keep track on that. private messages will get lost but here I can keep an eye of it.

There is a great way to compare code between 2 branches on github, so for your current idea of gatekeeper it would be this:

https://github.com/LineageOS/android_system_gatekeeper/compare/lineage-15.1...lineage-16.0

but.. digging just around is like finding the needle in a haystack so it would be a much better approach to grab logs (https://bit.do/logcat - option "oneshot", after trying to unlock) when that issue occurs.

**Comment by sdembis** [comment]
Thanks – didn’t know about the comparison function in GitHub. Will try for a logcat when issue occurs again.

S.

**Comment by sdembis** [comment]
@steadfasterX
I have since tested _only_ the gatekeeper.cpp as referenced in the link you posted with the differences between the 15.1 and 16.0 files incorporated in my own 15.1 build.  I have not had a recurrence of the lockscreen bootloop issue now in a week with the differences incorporated but will continue to test next week as well.  I have built another 15.1 rom with all the other file's differences incorporated as well from the link you provided and will test that after I have finished testing the build I'm running now. As the issue hasn't occurred so far, I have had no opportunity to provide a log of the issue occurring as yet but if it does I will provide a 1-shot log.

One thing I will mention, is that I have had two seemingly random instances of the torch turning on in my pocket - I have since turned on the _Prevent accidental wakeup_ as well turning off _Jump to camera_ and turning off _Long press for torch_ (I have never turned these two on and was surprised to find them turned on - I don't think it should be like this but rather the user having the option to turn them on, _if required_).

**Comment by steadfasterX** [comment]
> @steadfasterX
> I have since tested _only_ the gatekeeper.cpp as referenced in the link you posted with the differences between the 15.1 and 16.0 files incorporated in my own 15.1 build.

could you provide the commits you have done? if you haven't commited them do this in your repo dir:
`repo diff > mychanges.txt`
 
> One thing I will mention, is that I have had two seemingly random instances of the torch turning on in my pocket - I have since turned on the _Prevent accidental wakeup_ as well turning off _Jump to camera_ and turning off _Long press for torch_ (I have never turned these two on and was surprised to find them turned on - I don't think it should be like this but rather the user having the option to turn them on, _if required_).

Sounds not related? If that is a different issue a new issue report should be added while I never achieved that here (so logs logs..)

**Comment by sdembis** [comment]
@steadfasterX 

Reference this posting in LineageOS Gerritt:
https://review.lineageos.org/c/LineageOS/android_system_gatekeeper/+/258944
I brought this to the attention of Vasyl in LOS Gerritt on the 21st with respect to
getting it fixed and he contributed it yesterday and asked me to review it.
Hopefully will be merged permanently soon.  Line 244 deletion in the gatekeeper.cpp file has aleady been merged in the Sept security update merge. The comparison files you linked originally were done before that merge.

Yes, the torch issue is a separate issue, I just wanted to point out to you
that the *Jump to camera* and *Long press for torch *should not be be
turned on in your builds by default - it should be a user choice. I have
never turned these on and was surprised to see then turned on.  I will see
if if the issue recurs now before I post it as an actual issue.

On Mon, Sep 23, 2019 at 4:16 AM stay steadfast <notifications@github.com>
wrote:

> @steadfasterX <https://github.com/steadfasterX>
> I have since tested *only* the gatekeeper.cpp as referenced in the link
> you posted with the differences between the 15.1 and 16.0 files
> incorporated in my own 15.1 build.
>
ADDENDUM:
I have tested the change above for over a week now with the issue not recurring.
Now I have just installed another build with all the differences incorporated that were referenced in 
https://github.com/LineageOS/android_system_gatekeeper/compare/lineage-15.1...lineage-16.0
and will test this over the next week.
The first thing I noted with this new build is that when I booted up, I didn't have to go back and remove my lockscreen.db setting in TWRP.  I believe this may be a result of the merges pushed through in the September update to do with the gatekeeper functions with the first difference from the gatekkeoer.cpp file discussed above incorporated.

**Comment by sdembis** [comment]
@steadfasterX 

In reference to inclusion of [] in line 185 in the Lineage 15.1 gatekeeper.cpp file
"What does delete [] do in C ++?
delete() in C++
Delete is an operator that is used to destroy array and non-array(pointer) objects which are created by new expression. Delete can be used by either using Delete operator or Delete [ ] operator. New operator is used for dynamic memory allocation which puts variables on heap memory"
Link: https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&cad=rja&uact=8&ved=2ahUKEwiL0YuqrerkAhXKv54KHR_ZCmIQFjAEegQICxAJ&url=https%3A%2F%2Fwww.geeksforgeeks.org%2Fdelete-in-c%2F&usg=AOvVaw3tK49_V7_kKj_bj0kbUnO0

"The calling function is allocating memory with operator new[] , but freeing it with the scalar operator delete .
This is an error. According to the C++ standard and the Microsoft Visual C++ implementation, the result of this inconsistent operation is undefined. In addition, this error can cause the following problems, among others:
The constructors for the individual objects in the array are invoked, but the destructors are not invoked.
**Unexpected results are likely to occur, because the global (or class-specific) operator new and operator delete are not compatible with operator new[] and operator delete[] .**
Because the result of this code is undefined, **the precise consequences of this defect are difficult to predict. It can result in memory leaks in classes with destructors that deallocate memory, inconsistent behavior for classes with destructors that perform some semantically significant operation, or memory corruptions and crashes when operators have been overridden**. In other cases, the mismatch may be unimportant, depending on the implementation of the compiler and its libraries. PREfast for Drivers cannot always distinguish among these situations."
For General Interest:  https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&cad=rja&uact=8&ved=2ahUKEwiL0YuqrerkAhXKv54KHR_ZCmIQFjAGegQICxAU&url=http%3A%2F%2Fwww.voidcn.com%2Farticle%2Fp-kbkvpsqo-ux.html&usg=AOvVaw2PbwFPxlnJbV3TfdlBIxUG
