### ISSUE TITLE
NFC is not working lgH811 lineage-15.1-20190917-UNOFFICIAL-h811.zip

### ISSUE THREAD

**Issue by asterlxx** [Suicide-Squirrel/issues_oreo#25]
I cant use NFC... checking with lot of apps i can config is not working
LGH811
lineage-15.1-20190917-UNOFFICIAL-h811.zip
Any idea?

**Comment by steadfasterX** [comment]
without logs.. 

follow https://bit.do/logcat and there "specific issue" while testing your NFC app.
