### ISSUE TITLE
Call barring and Network Selection not available in 15.1

### ISSUE THREAD

**Issue by sdembis** [Suicide-Squirrel/issues_oreo#27]
@steadfasterX 

These issues have been brought up before.  To explore some telephone issues, I used the 16.0 android_packages_services_**Telephony-AndroidManifest.xml** file (https://github.com/LineageOS/android_packages_services_Telephony/tree/lineage-16.0) in a 15.1 build.

3 Build Fails occurred but when all the relevant problem lines were removed, the build succeeded. 

Interesting though is that the removed lines, corresponded to the issues of call blocking and network selection that are not available in the Lineage 15.1 build for H812.

Any thoughts/hints as to further exploration of these issues in order to fix them?

Appreciate all the work.
Regards, S.

**Comment by sdembis** [comment]
[15.1 Build Fails.txt](https://github.com/Suicide-Squirrel/issues_oreo/files/3776175/15.1.Build.Fails.txt)
Title should read:  Call barring and Network Selection **not working** in 15.1 as they show they're available but do not work.

Attached Build Fail file with the relevant lines below the fail notices.

**Comment by steadfasterX** [comment]
well back-porting such deep integrated stuff like telephony is like my attempt doing the same with the bluetooth stack (which failed ofc). I'm sorry but I cannot help you with that as it will be a PITA and even when it builds at the end the chances that it does what you like to do might be very small

**Comment by sdembis** [comment]
Understood.
