### ISSUE TITLE
Open Gapps for 8.1 arm 64 hangs on the completion step

### ISSUE THREAD

**Issue by sdembis** [Suicide-Squirrel/issues_oreo#29]
Very annoying, would appreciate a fix.
No problem on 16.0 but some users prefer using 15.1.
Would very much if you checked it out and see if it can be fixed easily.

Thank you.

**Comment by steadfasterX** [comment]
> Very annoying, would appreciate a fix.
> No problem on 16.0 but some users prefer using 15.1.
> Would very much if you checked it out and see if it can be fixed easily.
> 
> Thank you.

selinux permissive or enforcing? there was an issue in the past with a missing policy on pie..
