### ISSUE TITLE
Changing PIN/password breaks decrypt

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_oreo#3]
Steps to reproduce: 

Encrypt without pin/pass 
Reboot 
Set a PIN/pass 
Reboot 

Result: 
It will ask for pin/pass on boot but always fail to decrypt

**Comment by steadfasterX** [comment]
Likely fixed by commit https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/6e6ed2a1f5ac1ae7a9e22091f3c3094eef606f24

**Comment by ThePiGuy0** [comment]
I can confirm that this issue is now solved as following the above steps work along with changing the pattern/password etc (changes on pre-boot check as well)
