### ISSUE TITLE
No trim on encrypted devices possible

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_oreo#4]
https://forum.xda-developers.com/g4/development/lineageos-15-1-lg-g4-t3782722/post76458944

**Comment by pavlaras** [comment]
in AOSCP i use 
https://github.com/CypherOS/device_lge_g4-common/commit/aaeb940b7e097c831ffbd4e90d568a605952064a

Test build with it, encrypt and grab a log on boot to see if you have the same error anywhere in the log.
If not, then continuous trim is just what we need and no need to manual trimming.

**Comment by steadfasterX** [comment]
yea the _discard_ part ~~will be added soon~~ has been added already.. but why the hell do you disable the barriers? that's not a good idea and should be strictly avoided. 
btw that barrier=0 explains the data corruption issues we saw in the aoscp thread (under certain circumstances i.e. when battery dies).

wth.. barrier=0 is also in LOS that way..
ah it was added as @ThePiGuy0 [cp'ed](https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/f934e59f92f5f4369601ce18302a6e5e9fc17622) it..

fixed with: https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/54ba9055fa561e00530ce3c088d38fa4917d4dcf
