### ISSUE TITLE
Selinux is not enforced 

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_oreo#5]

**Comment by steadfasterX** [comment]
taken from https://bpaste.net/raw/8a81d5fb7f6f and https://bpaste.net/raw/d29c6da1c841

merged result:

[dmesg.txt](https://github.com/Suicide-Squirrel/issues_oreo/files/2423746/dmesg.txt)

**Comment by sreehax** [comment]
In AICP I can enable SELinux easily by flipping a switch in settings. 
![screenshot](https://user-images.githubusercontent.com/23709124/46899793-cd2e4c80-ce4c-11e8-8ce4-59c35bb17cd1.png)

**Comment by steadfasterX** [comment]
closed by several policies and finally:
 https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/1b41737a09d84
