### ISSUE TITLE
LiveDisplay doesn't work on LOS / RR

### ISSUE THREAD

**Issue by Bleuzen** [Suicide-Squirrel/issues_oreo#8]

**Comment by Bleuzen** [comment]
Did some research. The Lineage changelog contains now:
LiveDisplay has been rewritten as a binderized HAL

What I found out until now:
Here is what other devs did to other devices, for example op3:
https://review.lineageos.org/#/c/LineageOS/android_device_oneplus_oneplus3/+/207232/

These 2 commits could help:
https://github.com/LineageOS/android_device_oneplus_oneplus3/commit/1e38b4fa6a22cfe25c602048566c4c1048944a0f
https://github.com/LineageOS/android_device_oneplus_oneplus3/commit/8203e03d66942e4e1a55e49b267ab1fe02ade40d

**Comment by ThePiGuy0** [comment]
Yep we are missing that. I'll build it in and give it a go

**Comment by Bleuzen** [comment]
@pavlaras @steadfasterX 
I tryed it with the commits for the op3, but it didn't work.

After that I also tryed it with the legacy version as seen here:
https://github.com/LineageOS/android_device_oneplus_oneplus2/commit/75e4fbd1ab08134c7408316359a415ea3ff85d7a
Still doesn't work. But I have some more settings now. And you know what, they do even work :D
I can now set the saturation, hue, luminance and contrast.
But still not the colour temperature (the main LiveDisplay setting still resets itself to be off everytime).

So at least a little progress ;)

But now I have no idea anymore. I tryed the java, the new static, and the legacy version of LiveDisplay but they all don't work. In the logcat I also found nothing interesting. Maybe you do. (because I'm a beginner and never did something with android development before so don't know where to look at or maybe I'm just blind)

Logcat during I set LiveDisplay from Off to Night:
https://hastebin.com/ovucavigim.sql
and after that I went back from the LiveDisplay settings to the Display settings:
https://hastebin.com/ofurugatuz.sql

Oh and the big error starting at line 8 in the second one seems to have nothing to with LiveDisplay. It always appears when going back to the Display settings from another screen (for example when comming from Design).

**Comment by steadfasterX** [comment]
dunno if thats related :
~~~
05-28 00:03:42.132  1034  2566 E LightsService: Light requested not available on this device. 2
~~~

leading to:
https://github.com/LineageOS/android_frameworks_base/blob/lineage-15.1/services/core/jni/com_android_server_lights_LightsService.cpp#L142-L156

anyways the commits we see are all more or less the same.. here for mido:

https://github.com/mickaelmendes50/device_xiaomi_msm8953-common/commit/77ef80feb905426e7985e1a4179a85d3752c728f

the other error when switching in settings

~~~
ResourceType: No package identifier when getting value for resource number 0x00000000
~~~

maybe means we miss a definition in any of the >whatever< xmls somewhere?! im not good in that android  java crap though

**Comment by ThePiGuy0** [comment]
Yep I saw the ResourceType error as well

**Comment by steadfasterX** [comment]
@Bleuzen ur title say: LOS / RR so it works in aoscp?

**Comment by Bleuzen** [comment]
@steadfasterX yes, it works in AOSCP. But as I saw it, they use the default built-in android function for that, during LOS has it's own software to apply the filter.

EDIT: Yep, should be correct. Android has a built-in NightLight feature:

> Android 7.1.1 includes a feature called Night Light that reduces the amount of blue light emitted by the device display to better match the natural light of the user's time of day and location. Android 8.0 includes a feature that gives users more control over the intensity of the Night Light effect.

I think AOSCP uses that (only with a different GUI) during LOS uses it's own filter software, which is LiveDisplay.

**Comment by steadfasterX** [comment]
We should maybe stalk bullhead a bit.. 

https://forum.xda-developers.com/nexus-5x/orig-development/rom-lineageos-15-1-nexus-5x-bullhead-t3724575/post76703471

**Comment by pavlaras** [comment]
https://gerrit.cypheros.co/#/c/CypherOS/kernel_lge_msm8992/+/5457/
