### ISSUE TITLE
kernel: overheating / reboot

### ISSUE THREAD

**Issue by steadfasterX** [Suicide-Squirrel/issues_oreo#9]
user report:
https://forum.xda-developers.com/showpost.php?p=76679861&postcount=9

maybe also related:
https://forum.xda-developers.com/showpost.php?p=76672446&postcount=4532

maybe related to:
https://github.com/Suicide-Squirrel/android_device_lge_g4-common-LOS/commit/44093591394916660a5e5a1cdc6f06ce0191ad3e

**Comment by pavlaras** [comment]
Thermal Engine works differently depending the battery we use. (thats what i've seen)
People report that it gets hot and reboot but in my log i see that thermal engine works , it measures degC and lower CPU freq. instantly to help it lower it's temp to at least 47 degC.

It's not something i can fix by testing it at my phone.

**Comment by steadfasterX** [comment]
closed - no further reports and no confirmations
